services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: risk_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: risk_backend
    restart: always
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DB: risk_db
    ports:
      - "5000:5000"
    networks:
      - backend_network
    volumes:
      - ./backend:/app

  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: risk_frontend
    ports:
      - "5173:80"
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
    external: false

volumes:
  mysql_data:
